apiVersion: v1
kind: Namespace
metadata:
  name: chiny

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worketyamo-linux
  namespace: chiny
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worketyamo-linux
  template:
    metadata:
      labels:
        app: worketyamo-linux
    spec:
      containers:
        - name: react-app
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: worketyamo-linux
  namespace: chiny
spec:
  selector:
    app: worketyamo-linux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worketyamo-linux
  namespace: chiny
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - linux.worketyamo.com
      secretName: linux.worketyamo.com
  rules:
    - host: worketyamo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worketyamo-linux
                port:
                  number: 80

    - host: linux.worketyamo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worketyamo-linux
                port:
                  number: 80
